Check silicon revision before updating VR
AMDESE/vr-firmware-update pull request #17
Opened 2023-11-28 11:22 UTC by abinayaddhandapani

For XDPE and TDA parts , read the silicon revision from the VR device and check if the config file is compatible for update.

2023-12-01 20:20 UTC, supven01 requested changes

2023-12-01 20:20 UTC, supven01 commented on config/chalupa-vr.json
> +         "PmbusAddress":"0x43",
just thinking out loud...Do we even need "PmbusAddress" field? As it looks like SlaveAddress + PmbusTransOffset, where PmbusTransOffset = 0x30 would work without needing so many changes. Thoughts?

2023-12-04 14:49 UTC, mahkurap commented
[AMD Official Use Only - General]

Let us have adding the 0x30 as default logic to derive the PmBusAdress. If it is different, in future, we will add the PmBusAddress tag to override the default logic.

My 2 cents.

Mahesh

From: abinayaddhandapani ***@***.***>
Sent: Sunday, December 3, 2023 11:27 PM
To: AMDESE/vr-firmware-update ***@***.***>
Cc: Kurapati, Mahesh ***@***.***>; Review requested ***@***.***>
Subject: Re: [AMDESE/vr-firmware-update] Check silicon revision before updating VR (PR #17)

Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


@abinayaddhandapani commented on this pull request.

________________________________

In config/chalupa-vr.json<https://github.com/AMDESE/vr-firmware-update/pull/17#discussion_r1413386634>:

> @@ -52,16 +52,19 @@

       },

       {

          "SlaveAddress":"0x13",

+         "PmbusAddress":"0x43",

I have checked with the hardware team if there is any algorithm to get pmbus address from i2c address. There is no specific logic to derive it (though pmbus address = i2c address + 0x30 for the current platforms. So specified it in the config file without adding any inbuilt calculations.

—
Reply to this email directly, view it on GitHub<https://github.com/AMDESE/vr-firmware-update/pull/17#discussion_r1413386634>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCUUIJR3ENAWOBEZ7PMRYZLYHVNIVAVCNFSM6AAAAAA75SVL6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONRRGYZDGNRZGE>.
You are receiving this because your review was requested.Message ID: ***@***.******@***.***>>

2023-12-04 16:06 UTC, supven01 approved these changes

2023-12-04 16:06 UTC, merged