Update Infineon XDPE programming procedure
AMDESE/vr-firmware-update pull request #28
Opened 2024-09-17 18:33 UTC by aasboddu

Update the programming procedure as per the
AN001-XDPE1x2xx (XDPE192xx RevD & XDPE1D2xx RevB Programming Guide)

2024-09-18 02:34 UTC, abinayaddhandapani commented on src/vr_update_infineon_xdpe.cpp
> +        GET_CRC);
rc variable is not specified for print.

2024-09-18 02:37 UTC, abinayaddhandapani commented on src/vr_update_infineon_xdpe.cpp
> +        AVAIL_SPACE_BYTE);
rc is not specified in the print

2024-09-18 17:19 UTC, aasboddu commented on src/vr_update_infineon_xdpe.cpp
> +        GET_CRC);
ack

2024-09-18 17:19 UTC, aasboddu commented on src/vr_update_infineon_xdpe.cpp
> +        AVAIL_SPACE_BYTE);
ack

2024-09-19 13:08 UTC, abinayaddhandapani approved these changes

2024-09-20 17:21 UTC, supven01 requested changes

2024-09-20 17:21 UTC, supven01 commented on src/vr_update_infineon_xdpe.cpp
> +    usleep(20000);
magic number 20000

2024-09-20 17:21 UTC, supven01 commented on src/vr_update_infineon_xdpe.cpp
> +    std::string trim_header = "00000002";
magic number

2024-09-20 19:06 UTC, supven01 approved these changes

2024-09-20 19:06 UTC, supven01 commented on src/vr_update_infineon_xdpe.cpp
> +    wdata[INDEX_0] = 0x2;
This got changed from preprocessor macro to magic numbers.
I can overlook this for now, but please fix this next time.

2024-09-20 19:06 UTC, merged